Added integration test to ci pipeline

diff --git a/.github/workflows/ci-workflow.yml b/.github/workflows/ci-workflow.yml
--- a/.github/workflows/ci-workflow.yml
+++ b/.github/workflows/ci-workflow.yml
@@ -51,7 +51,7 @@ jobs:
 
       - name: Check code formatting
         run: |
-          if ! find source -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror; then
+          if ! find source -name '*.cpp' -o -name '*.hpp' | xargs clang-format --dry-run --Werror; then
             echo "::error::Code formatting issues were found. Please run 'clang-format' to fix them."
             exit 1
           else
@@ -87,6 +87,42 @@ jobs:
       - name: Sanitizer workflow
         run: cmake --workflow --preset ${{ matrix.preset }}
 
+  integration-test:
+    runs-on: ubuntu-latest
+    needs: tests
+    steps:
+      - name: Restore apt packages from cache
+        id: cache-apt
+        uses: awalsh128/cache-apt-pkgs-action@latest
+        with:
+          packages: cmake ninja-build g++ valgrind clang-format gcovr
+          version: 1.0.0
+
+      - name: Install dependencies
+        if: steps.cache-apt.outputs.cache-hit != 'true'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y cmake ninja-build g++
+    
+      - name: Checkout to repository
+        uses: actions/checkout@v4
+
+      - name: Build program
+        run: |
+          cmake --preset release
+          cmake --build --preset release
+
+      - name: Run program with test data and verify hash
+        run: |
+          HASH=$(cat test_data/ip_filter.tsv | ./build/release/source/ip_filter | md5sum | awk '{print $1}')
+          EXPECTED_HASH="24e7a7b2270daee89c64d3ca5fb3da1a"
+          if [ "$HASH" != "$EXPECTED_HASH" ]; then
+            echo "::error::Hash mismatch! Expected $EXPECTED_HASH, but got $HASH"
+            exit 1
+          else
+            echo "Hash verification successful: $HASH"
+          fi
+
   build-coverage-report:
     runs-on: ubuntu-latest
     needs: tests
@@ -117,7 +153,7 @@ jobs:
 
   release:
     runs-on: ubuntu-latest
-    needs: build-coverage-report
+    needs: integration-test
     if: startsWith(github.ref, 'refs/tags/release-')
 
     steps:
